import Navbar from "@/components/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import React from "react";

const inter = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Figma by Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-full h-screen inline-flex flex-col pt-[44px] pr-[39px] pb-[207.644px] pl-[41px]">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
